services:
  db:
    image: mysql:9.0.1
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      # MYSQL_DATABASE: lab_04
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - main
  books:
    build:
      context: ./zad_01
    ports:
      - 3000:3000
    restart: always
    networks:
      - main
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: zad_01
      DB_USER: zad_01
      DB_PASSWORD: password
      DB_DIALECT: mysql
      SECRET_KEY: sekret123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./zad_01:/usr/src/app
      - /usr/src/app/node_modules
  zad_02:
    build:
      context: ./zad_02
    ports:
      - 5000:3000
    restart: always
    networks:
      - main
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: zad_02
      DB_USER: zad_02
      DB_PASSWORD: password
      DB_DIALECT: mysql
      SECRET_KEY: sekret123
      BOOKS_API_ENDPOINT: http://books:3000/api/books
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./zad_02:/usr/src/app
      - /usr/src/app/node_modules
  zad_03:
    build:
      context: ./zad_03
    ports:
      - 4000:3000
    restart: always
    networks:
      - main
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: zad_03
      DB_USER: zad_03
      DB_PASSWORD: password
      DB_DIALECT: mysql
      SECRET_KEY: sekret123
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./zad_03:/usr/src/app
      - /usr/src/app/node_modules
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: toor
    depends_on:
      db:
        condition: service_healthy
    networks:
      - main
volumes:
  db_data: {}
networks:
  main:
